name: Scan code, execute unit test, update Flathub and mirror to opencode.net
on:
  push:
    branches:
      - "*"
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  njsscan:
    needs: snyk
    name: njsscan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: ". --sarif --output results.sarif || true"
      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
  codeql:
    needs: njsscan
    name: CodeQL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ["javascript"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up latest available Nodejs
        uses: actions/setup-node@master
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v4
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
  codecov:
    needs: codeql
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ["javascript"]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up latest available Nodejs
        uses: actions/setup-node@master
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run unit tests
        run: npm test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  mirror:
    needs: codecov
    name: Mirror code to opencode.net
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://www.opencode.net/ransome/sleek.git"
        env:
          FOLLOW_TAGS: "false"
          FORCE_PUSH: "false"
          GITLAB_HOSTNAME: "opencode.net"
          GITLAB_USERNAME: "ransome"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PAT }}
          GITLAB_PROJECT_ID: "1637"
          GITHUB_TOKEN: ${{ secrets.github_token }}
  flathub:
    name: Update commit id in Flathub repo
    runs-on: ubuntu-latest
    needs: mirror
    steps:
      - name: Trigger Flathub build
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.TRIGGER_FLATHUB_BUILD }}
          repository: ransome1/com.github.ransome1.sleek
          event-type: trigger-flathub-build
          client-payload: '{"commit_id": "${{ github.sha }}"}'
